import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import QueryClientProvider from "@/components/QueryClientProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryClientProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
          >
            {/* 仅在用户登录时显示导航栏 */}
            <SignedIn>
              <div className="w-1/5 h-screen bg-gray-50 fixed left-0 top-0">
                <Navbar />
              </div>
            </SignedIn>

            {/* 主内容区域 - 根据是否登录调整布局 */}
            <SignedOut>
              <div className="flex-1">
                <header className="flex justify-end items-center p-4 gap-4 h-16 bg-white">
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </header>
                <main className="p-4">{children}</main>
              </div>
            </SignedOut>

            <SignedIn>
              <div className="flex-1 ml-[20%]">
                <header className="flex justify-end items-center p-4 gap-4 h-16 bg-white">
                  <UserButton />
                </header>
                <main className="p-4">{children}</main>
              </div>
            </SignedIn>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  );
}
